### ISSUE TITLE
Question: does it work with TypeScript?

### ISSUE THREAD

**Issue by elektronik2k5** [EnoahNetzach/styled-components-stylefmt#2]
Thanks for creating this! (Question is in the title)

**Comment by elektronik2k5** [comment]
@EnoahNetzach ?

**Comment by EnoahNetzach** [comment]
Unfortunately I'm not sure, because I don't use typescript, so it isn't guaranteed.

If I'd to take a guess, I'd say no, because we use `babylon` directly, but feel free to try it out, and PRs are always well accepted!

**Comment by elektronik2k5** [comment]
Thank you!
